// CARD ACTIONS
export const ADD_CARD_START = "ADD_CARD_START"
export const ADD_CARD_SUCCESS = "ADD_CARD_SUCCESS"
export const ADD_CARD_FAIL = "ADD_CARD_FAIL"
export const ADD_CARD_END = "ADD_CARD_END"

// TOOLBAR ACTIONS
export const SORT_BY_MONSTER = "SORT_BY_MONSTER"
export const FIND_USER = "FIND_USER"