// CARD ACTIONS
export const ADD_CARD_START = "ADD_CARD_START"
export const ADD_CARD_SUCCESS = "ADD_CARD_SUCCESS"
export const ADD_CARD_FAIL = "ADD_CARD_FAIL"
export const ADD_CARD_END = "ADD_CARD_END"

// TOOLBAR ACTIONS
export const SORT_CARDS = "SORT_CARDS"
export const FIND_USER = "FIND_USER"

// PAGINATION ACTIONS
export const CHANGE_PAGE = "CHANGE_PAGE"
export const NEXT_PAGE = "NEXT_PAGE"
export const PREV_PAGE_REF = "PREV_PAGE_REF"

// AUTH ACTIONS
export const AUTH_START = "AUTH_START";
export const AUTH_END = "AUTH_END";
export const AUTH_SUCCESS = "AUTH_SUCCESS";
export const AUTH_FAIL = "AUTH_FAIL";
export const AUTH_REAUTHENTICATED = "AUTH_REAUTHENTICATED";
export const RESET_REAUTHENTICATED = "RESET_REAUTHENTICATED";
export const CONVERT_TO_PERM = "CONVERT_TO_PERM"
export const CHANGE_USERNAME = "CHANGE_USERNAME";
export const CHANGE_EMAIL = "CHANGE_EMAIL";
export const HANDLE_EMAIL_MODAL = "HANDLE_EMAIL_MODAL"
