export const lrhrMonsters = [
  { monster: "Anjanath" },
  { monster: "Azure Rathalos" },
  { monster: "Barroth" },
  { monster: "Black Diablos" },
  { monster: "Deviljho" },
  { monster: "Diablos" },
  { monster: "Dodogama" },
  { monster: "Great Girros" },
  { monster: "Great Jagras" },
  { monster: "Jyuratodus" },
  { monster: "Kirin" },
  { monster: "Kulu-Ya-Ku" },
  { monster: "Kulve Taroth" },
  { monster: "Kushala Daora" },
  { monster: "Lavasioth" },
  { monster: "Legiana" },
  { monster: "Lunastra" },
  { monster: "Nergigante" },
  { monster: "Odogaron" },
  { monster: "Paolumu" },
  { monster: "Pink Rathian" },
  { monster: "Pukei-Pukei" },
  { monster: "Radobaan" },
  { monster: "Rathalos" },
  { monster: "Rathian" },
  { monster: "Teostra" },
  { monster: "Tobi-Kadachi" },
  { monster: "Tzitzi-Ya-Ku" },
  { monster: "Uragaan" },
  { monster: "Vaal Hazak" },
  { monster: "Xeno'jiiva" },
  { monster: "Zorah Magdaros" },
]

export const mrMonsters = [
  { monster: "Acidic Glavenus" },
  { monster: "Ancient Leshen" },
  { monster: "Anjanath" },
  { monster: "Azure Rathalos" },
  { monster: "Banbaro" },
  { monster: "Barioth" },
  { monster: "Barroth" },
  { monster: "Bazelgeuse" },
  { monster: "Behemoth" },
  { monster: "Beotodus" },
  { monster: "Black Diablos" },
  { monster: "Blackveil Vaal Hazak" },
  { monster: "Brachydios" },
  { monster: "Brute Tigrex" },
  { monster: "Coral Pukei-Pukei" },
  { monster: "Deviljho" },
  { monster: "Diablos" },
  { monster: "Dodogama" },
  { monster: "Ebony Odogaron" },
  { monster: "Fulgur Anjanath" },
  { monster: "Furious Rajang" },
  { monster: "Glavenus" },
  { monster: "Gold Rathian" },
  { monster: "Great Girros" },
  { monster: "Great Jagras" },
  { monster: "Jyuratodus" },
  { monster: "Kirin" },
  { monster: "Kulu-Ya-Ku" },
  { monster: "Kulve Taroth" },
  { monster: "Kushala Daora" },
  { monster: "Lavasioth" },
  { monster: "Legiana" },
  { monster: "Leshen" },
  { monster: "Lunastra" },
  { monster: "Namielle" },
  { monster: "Nargacuga" },
  { monster: "Nergigante" },
  { monster: "Nightshade Paolumu" },
  { monster: "Odogaron" },
  { monster: "Paolumu" },
  { monster: "Pink Rathian" },
  { monster: "Pukei-Pukei" },
  { monster: "Radobaan" },
  { monster: "Raging Brachydios" },
  { monster: "Rajang" },
  { monster: "Rathalos" },
  { monster: "Rathian" },
  { monster: "Ruiner Nergigante" },
  { monster: "Safi'jiiva" },
  { monster: "Savage Deviljho" },
  { monster: "Scarred Yian Garuga" },
  { monster: "Seething Bazelgeuse" },
  { monster: "Shara Ishvalda" },
  { monster: "Shrieking Legiana" },
  { monster: "Silver Rathalos" },
  { monster: "Stygian Zinogre" },
  { monster: "Teostra" },
  { monster: "Tigrex" },
  { monster: "Tobi-Kadachi" },
  { monster: "Tzitzi-Ya-Ku" },
  { monster: "Uragaan" },
  { monster: "Vaal Hazak" },
  { monster: "Velkhana" },
  { monster: "Xeno'jiiva" },
  { monster: "Yian Garuga" },
  { monster: "Zinogre" },
  { monster: "Zorah Magdaros" },
]

